sudo: required
services:
  - docker

before_install:
  - docker build -t shipster/docker-react -f Dockerfile.dev .

script:
  - docker run stephengrider/docker-react npm run test -- --coverage

  #this is a comment