sudo: required
services:
  - docker

before_install:
  - docker build -t shipster/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true shipster/docker-react npm run test

  #this is a comment